target:
	gcc -Wall -o MyCompress MyCompress.c
	gcc -Wall -o MyDecompress MyDecompress.c
	gcc -Wall -o ForkCompress ForkCompress.c
	gcc -Wall -o PipeCompress PipeCompress.c
	gcc -Wall -o ParFork ParFork.c	
	gcc -Wall -o SHELL6 SHELL6.c
	gcc -Wall -o shell7 shell7.c
	gcc -Wall -o shell6_7_8 shell6_7_8.c
	gcc -Wall -o ParThread ParThread.c