target:
	gcc -Wall -o MyCompress2 MyCompress2.c
	gcc -Wall -o MyDecompress MyDecompress.c
	gcc -Wall -o ForkCompress ForkCompress.c
	gcc -Wall -o PipeCompress PipeCompress.c
	gcc -Wall -o ParFork ParFork.c	